apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret
spec:
  containers:
  - name: envars-container
    envFrom:
    - secretRef:
        name: mariadb-root
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
      requests:
        cpu: "1"
        memory: "128Mi"
