# templates/mariadb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
spec:
  ports:
  - name: http
    port: 3306
    targetPort: 3306
  selector:
    app: {{ .Release.Name }}-mariadb
